export const dataTest = [
  {
    name: "player 1",
    number: "01",
    photo: {},
    role: "captain",
    status: "player",
    pronouns: "elle",
    id: 0,
  },
  {
    name: "player 2",
    number: "11",
    photo: {},
    role: "",
    status: "player",
    pronouns: "ael",
    id: 1,
  },
  {
    name: "player 3",
    number: "015",
    photo: {},
    role: "",
    status: "player",
    pronouns: "il",
    id: 2,
  },
  {
    name: "player 4",
    number: "69",
    photo: {},
    role: "",
    status: "player",
    pronouns: "elle",
    id: 3,
  },
  {
    name: "player 5",
    number: "48",
    photo: {},
    role: "",
    status: "player",
    pronouns: "elle",
    id: 4,
  },
  {
    name: "player 6",
    number: "333",
    photo: {},
    role: "",
    status: "player",
    pronouns: "elle",
    id: 5,
  },
  {
    name: "player 7",
    number: "299",
    photo: {},
    role: "",
    status: "player",
    pronouns: "il",
    id: 6,
  },
  {
    name: "player 8",
    number: "25",
    photo: {},
    role: "",
    status: "player",
    pronouns: "il",
    id: 7,
  },
  {
    name: "player 9",
    number: "9999",
    photo: {},
    role: "",
    status: "player",
    pronouns: "elle",
    id: 8,
  },
  {
    name: "Bench",
    number: "",
    photo: {},
    role: "bench",
    status: "staff",
    pronouns: "elle",
    id: 9,
  },
  {
    name: "Line up manager",
    number: "",
    photo: {},
    role: "line-up",
    status: "staff",
    pronouns: "elle",
    id: 10,
  },
  {
    name: "Hello Statistiks",
    number: "",
    photo: {},
    role: "",
    status: "staff",
    pronouns: "elle",
    id: 11,
  },
];

export default dataTest;
